### ISSUE TITLE
Plugin will not accept price lower than 1 full bitcoin

### ISSUE THREAD

**Issue by justpaulgmx** [cryptoapi/Bitcoin-Payments-Appthemes#1]
If I try and price something at 0.5 BTC - It doesn't recognize it as valid and lists the job pack as free :-(

Any help would be appreciated. I guess it's possible it's the regular wordpress plugin which I also have installed. Not much of a techie, just looking for some help. 

Thanks, Paul.

P.S. I have priced in US Dollars in the short term as a solution, you can see the implementation at bitrecruit.com

**Comment by justpaulgmx** [comment]
It turned out to be a bug in the theme, not the plugin and I have resolved it so please consider closed.

**Comment by justpaulgmx** [comment]
P.S. It was only listing them as free in the admin area. The price was displayed correctly on the site. The only remaining issue is the two trailing digits after the decimal point as bitcoin could use more but that's workable for the forseeable and is a theme issue too so I can edit the code if needed down the road when bitcoin goes to the moon :-)

**Comment by cryptoapi** [comment]
RE> The only remaining issue is the two trailing digits after the decimal point as bitcoin 

We have already contacted AppThemes.com a few months ago about this.

**Comment by justpaulgmx** [comment]
I repriced all the pricing at bitrecruit.com from USD to BTC and all looked good as mentioned above. I just tried a checkout though and there are random bitcoin crumbs added to the total so it's not just 5 bitcoin, it's 5.00007118. The numbers appear to be random and not related to the price. This is the only bitcoin plugin that allows pricing in bitcoin which I want/need but it's not working and I'm at a dead end right now.

**Comment by cryptoapi** [comment]
It is correct.
HOW IT WORKS - https://gourl.io#section8

Our gateway is based on a different technology than standard gateways. It is fully able to integrate with Internet website pages and is more friendly for use by end website visitors. When any visitor goes to a website page they will see the page content and will see a cryptocoin payment box (For example, Pay-Per-Download). Some websites with high traffic show more than 10,000 pages are viewed per hour and our installed gourl cryptocoin payment box is seen on those pages also. It is impossible for each payment box to show a new unique generated bitcoin payment address for each website visitor because our system would then need to store millions of temporary bitcoin addresses and would be slow in its operation (For example - a 10,000 pages view per hour/payment boxes x 200 high traffic websites with our payment gateway would require no less than 2,000,000 temporary bitcoin addresses).

We add to your amount in the payment box a small fraction after the decimal point to uniquely identify each of your visitors individually. Users who have made payments with wrong amount are not recognised and you need to process such payments manually. You can see a separate table on your account with details of incorrect/unrecognised received payments.

We forward you ALL coins received on your internal wallet address/es including all payments with incorrect amounts (unrecognised payments).
